"""Simplified passive-brachiation model package.

The package provides a readable framework for a two-link brachiation model
on an inclined slope:

* one endpoint is attached to a support point,
* the middle joint is a revolute joint,
* the other endpoint swings freely,
* when the free endpoint contacts the slope surface, a switch policy decides
  whether to transfer the support hand (SWITCH), release the contact point
  (NO_SWITCH), or enter double-support rest (DWELL).
"""

from .kinematics import LinkPoints, Slope, forward_kinematics
from .model import BrachiationParameters, BrachiationState, TwoLinkBrachiationModel
from .analysis import (
    impact_indices,
    phase_mask,
    release_indices,
    release_q2_values,
    release_stride_distances,
    samples_to_arrays,
    support_arclengths,
    tail_half_range,
    tail_std,
)
from .com_continuation import (
    ComContinuationRow,
    ComValidation,
    SymmetricComContinuation,
    com_fractions_from_offset,
    parameters_with_symmetric_com_offset,
    run_symmetric_com_continuation,
    validate_com_point,
)
from .experiments import (
    FixedGaitFreeRun,
    PassiveSetup,
    StrideFixedPointSearchResult,
    StrideFixedPointTrial,
    make_default_uniform_setup,
    run_fixed_gait_free_run,
    run_passive_simulation,
    scan_stride_fixed_points,
    selected_stride_summary,
)
from .policies import (
    always_switch_policy,
    dwell_policy,
    never_switch_policy,
    zero_endpoint_force_policy,
    zero_generalized_force_policy,
    zero_torque_policy,
)
from .shooting import (
    ContinuationPoint,
    ContinuationResult,
    ElbowSectionLegality,
    FixedPoint1DResult,
    FixedPointBracket,
    GridSearchResult,
    ResidualScanResult,
    ShootingResult,
    StrideMapEvaluation,
    continue_fixed_point_branch,
    evaluate_elbow_below_slope_section,
    evaluate_passive_brachiation_q2_stride,
    evaluate_passive_brachiation_stride,
    find_fixed_points_1d,
    finite_difference_jacobian,
    grid_search_initial_guesses,
    ik_from_stride_distance,
    ik_from_q2_on_slope,
    make_iterated_stride_map,
    make_passive_brachiation_q2_stride_map,
    make_passive_brachiation_feasibility_check,
    make_passive_brachiation_stride_map,
    make_q2_feasibility_check,
    newton_shoot,
    poincare_jacobian_eigenvalues_1d,
    q2_from_release_state,
    residual_sign_change_scan,
    scalar_fixed_point_residual,
    solve_fixed_point_bracket_1d,
    stride_distance_from_q2,
    stride_distance_from_point,
    stride_point_from_distance,
    validate_release_section_geometry,
)
from .simulation import SimPhase, SimulationSample, simulate
from .switching import (
    CollisionContext,
    CollisionModel,
    CollisionMode,
    ImpactResult,
    SwitchDecision,
    SwitchResult,
    apply_collision_model,
    detect_slope_impact,
    apply_switch_decision,
    compute_full_grab_collision_velocity,
    compute_plastic_collision_velocity,
)

__all__ = [
    # model
    "BrachiationParameters",
    "BrachiationState",
    "TwoLinkBrachiationModel",
    # analysis
    "impact_indices",
    "phase_mask",
    "release_indices",
    "release_q2_values",
    "release_stride_distances",
    "samples_to_arrays",
    "support_arclengths",
    "tail_half_range",
    "tail_std",
    # experiment workflows
    "FixedGaitFreeRun",
    "PassiveSetup",
    "StrideFixedPointSearchResult",
    "StrideFixedPointTrial",
    "make_default_uniform_setup",
    "run_fixed_gait_free_run",
    "run_passive_simulation",
    "scan_stride_fixed_points",
    "selected_stride_summary",
    # COM continuation
    "ComContinuationRow",
    "ComValidation",
    "SymmetricComContinuation",
    "com_fractions_from_offset",
    "parameters_with_symmetric_com_offset",
    "run_symmetric_com_continuation",
    "validate_com_point",
    # policies
    "always_switch_policy",
    "dwell_policy",
    "never_switch_policy",
    "zero_endpoint_force_policy",
    "zero_generalized_force_policy",
    "zero_torque_policy",
    # shooting
    "ElbowSectionLegality",
    "ContinuationPoint",
    "ContinuationResult",
    "FixedPoint1DResult",
    "FixedPointBracket",
    "GridSearchResult",
    "ResidualScanResult",
    "ShootingResult",
    "StrideMapEvaluation",
    "continue_fixed_point_branch",
    "evaluate_elbow_below_slope_section",
    "evaluate_passive_brachiation_q2_stride",
    "evaluate_passive_brachiation_stride",
    "find_fixed_points_1d",
    "finite_difference_jacobian",
    "grid_search_initial_guesses",
    "ik_from_stride_distance",
    "ik_from_q2_on_slope",
    "make_iterated_stride_map",
    "make_passive_brachiation_q2_stride_map",
    "make_passive_brachiation_feasibility_check",
    "make_passive_brachiation_stride_map",
    "make_q2_feasibility_check",
    "newton_shoot",
    "poincare_jacobian_eigenvalues_1d",
    "q2_from_release_state",
    "residual_sign_change_scan",
    "scalar_fixed_point_residual",
    "solve_fixed_point_bracket_1d",
    "stride_distance_from_q2",
    "stride_distance_from_point",
    "stride_point_from_distance",
    "validate_release_section_geometry",
    # kinematics
    "LinkPoints",
    "Slope",
    "forward_kinematics",
    # switching
    "CollisionContext",
    "CollisionModel",
    "CollisionMode",
    "SwitchDecision",
    "SwitchResult",
    "ImpactResult",
    "apply_collision_model",
    "detect_slope_impact",
    "apply_switch_decision",
    "compute_full_grab_collision_velocity",
    "compute_plastic_collision_velocity",
    # simulation
    "SimPhase",
    "SimulationSample",
    "simulate",
]
